### ISSUE TITLE
Comment plugin and Register not working

### ISSUE THREAD

**Issue by sozof** [sjarvela/kloudspeaker#49]
i cant get comment and register to work in last version 2.7 this is the issues:

register : 
TypeError: app.openPage is not a function
app.openPage('registration/new');

comment plugin : 
TypeError: that._timestampFormatter is undefined
comments[i].time = that._timestampFormatter.format(utils.parseInternalTime(comme...

**Comment by sjarvela** [comment]
Should be fixed in 2.7.2, lots have changed after 2.7, and at least cannot reproduce errors in this version.

**Comment by oupala** [comment]
This issue should be re-opened.

I've just upgraded my instance to version 2.7.5 and I have the exact same error.

I already had this problem with my previous version 2.6.15.

In addition, the label "Registrations" from the "pluginRegistrationAdminNavTitle" does not appear in the menu.

It looks like the plugin is not loaded at startup.

I'm also using the french locale, but the french localization file is almost empty. I think it used to be not that empty. Maybe some content have been lost...

**Comment by sjarvela** [comment]
I can't see any errors, I've tried comments plugin and registration. Are you sure you have updated all files, also backend and backend/plugins folder?

French localizations may very well be missing, I cannot translate them so people have sent me updated localization files whenever they have seen texts missing.

**Comment by oupala** [comment]
In my case, it might have been related to a translation where the i18n json was faulty (missing commas). Check that in a json linter if you encounter such problem.
